<?php

namespace parrotposter;

defined('ABSPATH') || exit;

/**
 * RFC 8785 JSON Canonicalization Scheme (JCS) — PHP port of back-app's
 * `pipeline_domain::signing::canonical_json_bytes` (TASK-002-BE-47, `serde_json_canonicalizer`
 * crate), used to Ed25519-verify `PluginOutboundTask.payload_signature` (TASK-002-WP-09,
 * SPEC-002-03 §7.2). Must produce byte-identical output to the Rust side for the same input —
 * approximating JCS as "sorted keys + compact json_encode" is NOT sufficient (see per-method
 * notes below for the specific footguns: UTF-16 key ordering, ECMAScript number formatting,
 * solidus/unicode escaping).
 *
 * Verified byte-for-byte against golden vectors generated by a real Rust binary using the exact
 * crates BE-47 depends on (serde_json_canonicalizer 0.2.0, ed25519-dalek 2.2.0) — see WP-09's
 * report for the vector set and how they were produced; not just internal PHP self-consistency.
 */
class CanonicalJson
{
	/**
	 * @param mixed $value Decoded JSON value: null, bool, int, float, string, or PHP array
	 *                      (list arrays -> JSON arrays, non-list/assoc arrays -> JSON objects —
	 *                      same convention as `json_decode($x, true)` output, which is what
	 *                      `OutboundTaskDispatch` feeds this).
	 */
	public static function canonicalize($value): string
	{
		return self::encode_value($value);
	}

	/**
	 * @param mixed $value
	 */
	private static function encode_value($value): string
	{
		if ($value === null) {
			return 'null';
		}
		if (is_bool($value)) {
			return $value ? 'true' : 'false';
		}
		if (is_int($value) || is_float($value)) {
			return self::format_number($value);
		}
		if (is_string($value)) {
			return self::encode_string($value);
		}
		if (is_array($value)) {
			return self::is_list($value) ? self::encode_array($value) : self::encode_object($value);
		}

		throw new \InvalidArgumentException('Unsupported value type for canonical JSON: ' . gettype($value));
	}

	/**
	 * PHP 7.4-compatible replacement for `array_is_list()` (PHP 8.1+) — this plugin's minimum
	 * supported PHP version (see `parrotposter.php` header) predates it.
	 *
	 * @param array<mixed> $arr
	 */
	private static function is_list(array $arr): bool
	{
		if ($arr === []) {
			return true;
		}

		return array_keys($arr) === range(0, count($arr) - 1);
	}

	/**
	 * @param list<mixed> $value
	 */
	private static function encode_array(array $value): string
	{
		$parts = [];
		foreach ($value as $item) {
			$parts[] = self::encode_value($item);
		}

		return '[' . implode(',', $parts) . ']';
	}

	/**
	 * Objects: properties sorted by the UTF-16 code unit sequence of the (already-decoded) key
	 * string (RFC 8785 §3.2.3) — NOT byte order, NOT Unicode codepoint order. These diverge for
	 * any key containing a codepoint above U+FFFF (astral plane): its UTF-16 surrogate pair
	 * starts at 0xD800-0xDBFF, which sorts *before* any BMP codepoint in the 0xE000-0xFFFF range
	 * even though the astral codepoint itself is numerically larger. Matches
	 * `serde_json_canonicalizer`'s `JsonProperty` ordering exactly (`jcs.rs`) — verified against
	 * a golden vector built specifically to hit this divergence (WP-09 report).
	 *
	 * @param array<string, mixed> $value
	 */
	private static function encode_object(array $value): string
	{
		$entries = [];
		foreach ($value as $key => $item) {
			$entries[] = [
				'key' => (string) $key,
				'sort_key' => self::utf16_code_units((string) $key),
				'value' => self::encode_value($item),
			];
		}

		usort($entries, static function (array $a, array $b): int {
			return self::compare_u16_sequences($a['sort_key'], $b['sort_key']);
		});

		$parts = [];
		foreach ($entries as $entry) {
			$parts[] = self::encode_string($entry['key']) . ':' . $entry['value'];
		}

		return '{' . implode(',', $parts) . '}';
	}

	/**
	 * @return list<int> unsigned 16-bit code units (surrogate pairs kept as two units, matching
	 *                    Rust's `str::encode_utf16()`)
	 */
	private static function utf16_code_units(string $utf8): array
	{
		$utf16be = mb_convert_encoding($utf8, 'UTF-16BE', 'UTF-8');
		$units = [];
		$len = strlen($utf16be);
		for ($i = 0; $i < $len; $i += 2) {
			$units[] = (ord($utf16be[$i]) << 8) | ord($utf16be[$i + 1]);
		}

		return $units;
	}

	/**
	 * @param list<int> $a
	 * @param list<int> $b
	 */
	private static function compare_u16_sequences(array $a, array $b): int
	{
		$len = min(count($a), count($b));
		for ($i = 0; $i < $len; $i++) {
			if ($a[$i] !== $b[$i]) {
				return $a[$i] <=> $b[$i];
			}
		}

		return count($a) <=> count($b);
	}

	/**
	 * JSON string escaping per RFC 8785 / RFC 8259: quote and backslash escaped; ASCII control
	 * chars (U+0000-U+001F) escaped (named escapes for \b \f \n \r \t, \u00XX otherwise); solidus
	 * `/` deliberately left **unescaped** (matches the JS reference `canonicalize` package and
	 * `serde_json_canonicalizer`'s explicit override — RFC 8785 §3.2.2.2 does not require
	 * escaping it, and `"\/"  === "/"` in JS); all other bytes (multi-byte UTF-8 for non-ASCII /
	 * astral characters) are written through unescaped, as raw UTF-8 — JCS output is UTF-8, not
	 * ASCII-safe JSON.
	 */
	private static function encode_string(string $utf8): string
	{
		$out = '"';
		$len = strlen($utf8);
		$i = 0;
		while ($i < $len) {
			$byte = $utf8[$i];
			$ord = ord($byte);
			if ($ord < 0x80) {
				switch ($byte) {
					case '"':
						$out .= '\\"';
						break;
					case '\\':
						$out .= '\\\\';
						break;
					case "\x08":
						$out .= '\\b';
						break;
					case "\x0C":
						$out .= '\\f';
						break;
					case "\n":
						$out .= '\\n';
						break;
					case "\r":
						$out .= '\\r';
						break;
					case "\t":
						$out .= '\\t';
						break;
					default:
						if ($ord < 0x20) {
							$out .= sprintf('\\u%04x', $ord);
						} else {
							// includes solidus '/' — intentionally not escaped
							$out .= $byte;
						}
				}
				$i++;
			} else {
				// Multi-byte UTF-8 sequence: pass through raw.
				$seq_len = self::utf8_sequence_length($ord);
				$out .= substr($utf8, $i, $seq_len);
				$i += $seq_len;
			}
		}

		return $out . '"';
	}

	private static function utf8_sequence_length(int $first_byte_ord): int
	{
		if (($first_byte_ord & 0xE0) === 0xC0) {
			return 2;
		}
		if (($first_byte_ord & 0xF0) === 0xE0) {
			return 3;
		}
		if (($first_byte_ord & 0xF8) === 0xF0) {
			return 4;
		}

		return 1; // malformed lead byte — advance by 1 to avoid an infinite loop
	}

	/**
	 * All JSON numbers are formatted as if converted to an IEEE-754 double, then rendered via
	 * the ECMAScript `Number::toString` algorithm (RFC 8785 §3.2.2.3 — JCS mandates
	 * ECMAScript's `NumberToString` for every numeric value, integers included; there is no
	 * separate integer format, and large integers lose precision beyond 2^53 exactly like on the
	 * Rust side, which also casts every integer type `as f64` before formatting). Matches
	 * `serde_json_canonicalizer::jcs::JcsFormatter::write_f64` (`ryu_js`, a V8-compatible
	 * shortest-round-trip formatter) byte-for-byte — verified against the crate's own RFC
	 * Appendix B + v8-compat integer test vectors (TASK-002-WP-09 report).
	 *
	 * @param int|float $num
	 */
	private static function format_number($num): string
	{
		$f = (float) $num;
		if ($f === 0.0) {
			// Collapses +0/-0 to "0", matching JcsFormatter (ryu_js formats -0.0 as "0").
			return '0';
		}
		if (!is_finite($f)) {
			throw new \InvalidArgumentException('NaN and +/-Infinity are not permitted in JSON (JCS)');
		}

		$sign = $f < 0 ? '-' : '';
		$abs = abs($f);
		[$digits, $n] = self::shortest_digits_and_decimal_exponent($abs);
		$k = strlen($digits);

		if ($k <= $n && $n <= 21) {
			$body = $digits . str_repeat('0', $n - $k);
		} elseif ($n > 0 && $n <= 21) {
			$body = substr($digits, 0, $n) . '.' . substr($digits, $n);
		} elseif ($n > -6 && $n <= 0) {
			$body = '0.' . str_repeat('0', -$n) . $digits;
		} else {
			$e = $n - 1;
			$mantissa = $k === 1 ? $digits : substr($digits, 0, 1) . '.' . substr($digits, 1);
			$body = $mantissa . 'e' . ($e >= 0 ? '+' : '-') . abs($e);
		}

		return $sign . $body;
	}

	/**
	 * Shortest decimal digit string `d1d2...dk` (no padding beyond what's needed) and decimal
	 * exponent `n` such that `0.d1d2...dk * 10^n` round-trips back to the exact double `$abs`
	 * (`$abs` > 0, finite). Found by searching precision 1..17 for the first that round-trips —
	 * the standard technique for shortest-round-trip decimal formatting without depending on a
	 * specific dtoa library: for the minimal such precision, the correctly-rounded decimal at
	 * that precision (which `sprintf('%.Ne', ...)` produces, backed by the platform libc's
	 * correctly-rounded float formatting) is guaranteed to be among the round-tripping
	 * candidates. Independent of the `serialize_precision` ini setting (does not use
	 * `json_encode`), so it behaves identically across hosting environments.
	 *
	 * @return array{0: string, 1: int}
	 */
	private static function shortest_digits_and_decimal_exponent(float $abs): array
	{
		for ($p = 1; $p <= 17; $p++) {
			$formatted = sprintf('%.' . ($p - 1) . 'e', $abs);
			if ((float) $formatted === $abs) {
				return self::parse_sci_notation($formatted);
			}
		}

		// Unreachable for any finite double (17 significant digits always round-trips), kept as
		// a defensive fallback rather than a thrown error.
		return self::parse_sci_notation(sprintf('%.16e', $abs));
	}

	/**
	 * @return array{0: string, 1: int}
	 */
	private static function parse_sci_notation(string $formatted): array
	{
		[$mantissa, $exp] = explode('e', $formatted);
		$digits = str_replace('.', '', $mantissa);

		return [$digits, ((int) $exp) + 1];
	}
}
